// Angular_tasks/angular-crash/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from '../../Task';
import { UiService } from '../../services/ui.service'; 
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {
  text: string;
  day: string;
  reminder: boolean = false;
  showAddTask: boolean = false;
  subscription: Subscription;
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter();

  constructor(private uiService:UiService) {
    this.subscription = this.uiService.onToggle().subscribe((value) => this.showAddTask = value);

  }

  ngOnInit(): void {
  }

  onSubmit() {
    if(!this.text) {
      alert("Please add text");
      return;
    }

    const newTask = {
      text: this.text,
      day:  this.day,
      reminder:  this.reminder
    }

    this.onAddTask.emit(newTask);
    this.text = '';
    this.day = '';
    this.reminder = false;
  }
}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" [(ngModel)]="text" id="text"  placeholder="Add Task">    
    </div>
    <div class="form-control">
        <label for="day">Day and Time</label>
        <input type="text" name="day" [(ngModel)]="day" id="day"  placeholder="Add Day and Time">    
    </div>
    <div class="form-control form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder">    
    </div>
    <input type="submit" value="Save Task" class="btn btn-block">
</form>

// reactCrash/react-task-tracker/src/components/AddTask.js
import { useState } from 'react'

const AddTask = ({ onAdd }) => {
    const [ text, setText] = useState('');
    const [ day, setDay] = useState('');
    const [ reminder, setReminder] = useState(false);

    const onSubmit = (e) => {
        e.preventDefault();

        if(!text) {
            alert('Please add a task');
            return;
        }
        
        onAdd({ text, day, reminder });
        setText('');
        setDay('');
        setReminder(false);
    }

    return (
    <form className="add-form" onSubmit={onSubmit}>
        <div className="form-control">
            <label>Task</label>
            <input type="text" value={text} onChange={(e) => setText(e.target.value)} placeholder='Add Task' />
        </div>
        <div className="form-control">
            <label>Day & Time</label>
            <input type="text" value={day} onChange={(e) => setDay(e.target.value)}placeholder='Add Day & Time' />
        </div>
        <div className="form-control form-control-check">
            <label>Set Reminder</label>
            <input type="checkbox" checked={reminder} value={reminder} onChange={(e) => setReminder(e.currentTarget.checked)}/>
        </div>

        <input type="submit" value="Save Task" className="btn btn-block"/>
    </form>
  )
}

export default AddTask
